# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Your Title
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://setgraphic.com/" # the base hostname & protocol for your site
lang: US
twitter_username: setgraphic
github_username: setgraphic
linkedin_username: setgraphic
UA: UA-XXXXXXX-X

# Build settings
markdown: kramdown
exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
  - gulpfile.*
  - package.json
  - README.md
  - makefile
keep_files:
  - assets
  - css/main.css
  - css/main.min.css
  - scripts/main.js
  - scripts/main.min.js
