# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:              Setgraphic
brand:              Setgraphic
description:        Setgraphic, interaktives Kreativ & Webdesign Studio in Frankfurt / Main. Wir entwickeln Webseiten + Blogs zu fairen Preisen + SEO &, online Strategien.
baseurl:            "" # the subpath of your site, e.g. /setgraphic
url:                "" # the base hostname & protocol for your site
lang:               de-DE
twitter_username:   setgraphic
github_username:    stphn
linkedin_username:  goeuriot
UA:                 UA-XXXXXXX-X # google analytic code
permalink:          pretty

# Scripts to prepend in start.html
styles:
  - /bower/normalize-css/normalize.css
  - /bower/flickity/dist/flickity.css

# Scripts to prepend in end.html
scripts:
  - /bower/flickity/dist/flickity.pkgd.min.js

collections:
  portfolios:
    output: true
    permalink: /portfolios/:path/

# Build settings
markdown: kramdown

exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
  - gulpfile.*
  - package.json
  - README.md
  - makefile
  - appveyor.yml
  - bower.json
  - tasks
  - Rakefile
keep_files:
  - assets
  - css/main.css
  - css/main.min.css
  - scripts/main.js
  - scripts/main.min.js

# Atom.io settings
atom:
  postDirs:
    - posts/_drafts
    - posts/_posts
  defaultPostDir: _drafts
