# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.


description:
  en: Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
  fr: Écrivez une super description de votre nouveau site ici. Vous pouvez modifier cette ligne dans _config.yml. Elle apparaîtra dans la balise meta description (pour les résultats sur Google) et dans le fil RSS feed.xml.

index:
  en:
  fr: accueil.html

feed:
  en: /feed.xml
  fr: /flux.xml
# Site settings
title:              Setgraphic
brand:              Setgraphic
description:        Setgraphic, interaktives Kreativ & Webdesign Studio in Frankfurt / Main. Wir entwickeln Webseiten + Blogs zu fairen Preisen + SEO &, online Strategien.
baseurl:            "" # the subpath of your site, e.g. /setgraphic
url:                "http://localhost:3000" # the base hostname & protocol for your site
twitter_username:   setgraphic
github_username:    stphn
linkedin_username:  goeuriot
UA:                 UA-XXXXXXX-X # google analytic code
permalink:          pretty

include:
  - _pages
  - scope:
      path: '_pages'
    values:
      permalink: /:basename/

# Scripts to prepend in start.html
styles:
  - /bower/normalize-css/normalize.css
  - /bower/flickity/dist/flickity.css


# Scripts to prepend in end.html
scripts:
  - /bower/flickity/dist/flickity.pkgd.min.js
  - /bower/headroom.js/dist/headroom.min.js

collections:
  portfolios:
    output: true
    permalink: /portfolios/:path/

# Build settings
markdown: kramdown

exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
  - gulpfile.*
  - package.json
  - README.md
  - makefile
  - appveyor.yml
  - bower.json
  - tasks
  - Rakefile
  - npm-debug.log
keep_files:
  - assets
  - css/main.css
  - css/main.min.css
  - scripts/main.js
  - scripts/main.min.js

# Atom.io settings
atom:
  postDirs:
    - posts/_drafts
    - posts/_posts
  defaultPostDir: _drafts
